name: Theme deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install Shopify Theme Kit
        run: npm install -g @shopify/themekit
      - name: Add npm global bin to PATH
        run: echo "PATH=$(npm bin -g):\$PATH" >> $GITHUB_ENV
      - name: Verify Theme Kit Installation
        run: theme --version
      - name: Deploy to Shopify
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
        run: theme deploy --password=$SHOPIFY_PASSWORD --store=$SHOPIFY_STORE --themeid=Dawn